### ISSUE TITLE
Calculate mumax3 subregions

### ISSUE THREAD

**Issue by lang-m** [ubermag/mumax3c#14]
- [x] Add code to mumax3c
- [x] Add Ms to mx3 files
- [x] Add `region_relator` to `system`
- [x] Informative error message
- [x] Use mesh to create slices

**Comment by samjrholt** [comment]
@lang-m Please could you check the code and also add the slicing you were talking about from mesh. The relevant code is now in `mumax3c/scripts/util.py`

**Comment by samjrholt** [comment]
@lang-m I've found the relevant code so can ad it myself. I will let you know when it is done.
